SHOW DATABASES;

USE NBA_GRUPO6;

CREATE TABLE games
(GAME_DATE_EST DATE,	GAME_ID VARCHAR(20), GAME_STATUS_TEXT TEXT,	HOME_TEAM_ID VARCHAR(20),	VISITOR_TEAM_ID VARCHAR(20),	SEASON VARCHAR(20),	
TEAM_ID_home VARCHAR(20),	PTS_home INT,	FG_PCT_home DOUBLE,	FT_PCT_home DOUBLE,	FG3_PCT_home DOUBLE, AST_home INT,	REB_home INT,	TEAM_ID_away INT,	
PTS_away INT,	FG_PCT_away DOUBLE,	FT_PCT_away DOUBLE,	FG3_PCT_away DOUBLE,	AST_away INT,	REB_away INT,	HOME_TEAM_WINS INT);

SHOW TABLES;

SELECT * FROM games;

-- 'C:/Users/VINÍCIUS/Desktop/Projeto-Modulo2/Resilia_Projeto_MOD2/NBA games data/(ARQUIVO).csv' 
LOAD DATA LOCAL INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/games.csv'
INTO TABLE games
FIELDS TERMINATED BY ','
IGNORE 1 LINES; 

SELECT * FROM games;