SHOW DATABASES;

USE NBA_GRUPO6;                               

SHOW TABLES;

SELECT * FROM games_details;

CREATE TABLE games_details(
GAME_ID VARCHAR(20),
TEAM_ID VARCHAR(20),
TEAM_ABBREVIATION VARCHAR(20), 
TEAM_CITY VARCHAR(20),
PLAYER_ID VARCHAR(20),
PLAYER_NAME VARCHAR(20),
START_POSITION TEXT,
COMMENTA TEXT,
MIN DOUBLE,
FGM DOUBLE,
FGA DOUBLE,
FG_PCT DOUBLE,
FG3M DOUBLE,
FG3A DOUBLE,
FG3_PCT DOUBLE,
FTM DOUBLE,
FTA DOUBLE,
FT_PCT DOUBLE,
OREB DOUBLE,
DREB DOUBLE,
REB DOUBLE,
AST DOUBLE,
STL DOUBLE,
BLK DOUBLE,
TurnOver DOUBLE, 
PF DOUBLE,
PTS DOUBLE,
PLUS_MINUS DOUBLE);

-- 'C:/Users/VINÍCIUS/Desktop/Projeto-Modulo2/Resilia_Projeto_MOD2/NBA games data/games_details-resumida.csv' 
LOAD DATA LOCAL INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/games_details.csv'
INTO TABLE games_details
FIELDS TERMINATED BY ','
IGNORE 1 LINES; 

show variables like "secure_file_priv";

SELECT * FROM games_details;