SHOW DATABASES;

USE NBA_GRUPO6;

CREATE TABLE teams
(LEAGUE_ID VARCHAR(20), TEAM_ID VARCHAR(20),	MIN_YEAR INT,	MAX_YEAR INT,	ABBREVIATION TEXT, 	NICKNAME VARCHAR(15),
YEARFOUNDED INT,	CITY TEXT,	ARENA TEXT,	ARENACAPACITY INT , 	DONO VARCHAR(50),	GENERALMANAGER	VARCHAR(50),
HEADCOACH VARCHAR(50),	DLEAGUEAFFILIATION VARCHAR(50) );

SHOW TABLES;

SELECT * FROM teams;

-- 'C:/Users/VINÍCIUS/Desktop/Projeto-Modulo2/Resilia_Projeto_MOD2/NBA games data/(ARQUIVO).csv' 
LOAD DATA LOCAL INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/teams.csv'
INTO TABLE teams
FIELDS TERMINATED BY ','
IGNORE 1 LINES; 

SELECT * FROM teams;
