SHOW DATABASES;
USE NBA_GRUPO6;
CREATE TABLE ranking
(TEAM_ID VARCHAR(20),	LEAGUE_ID VARCHAR(20), 	SEASON_ID VARCHAR(20),	STANDINGSDATE DATE,	CONFERENCE TEXT,
TEAM TEXT,	G INT,	W INT,	L INT,	W_PCT DOUBLE,	HOME_RECORD VARCHAR(11),	ROAD_RECORD VARCHAR(11) );

SHOW TABLES;
SELECT * FROM ranking;

-- 'C:/Users/VINÍCIUS/Desktop/Projeto-Modulo2/Resilia_Projeto_MOD2/NBA games data/(ARQUIVO).csv' 
LOAD DATA LOCAL INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/ranking.csv'
INTO TABLE ranking
FIELDS TERMINATED BY ','
IGNORE 1 LINES; 

SELECT * FROM ranking;
